---
# file: roles/common/tasks/resolv_conf.yml

- name: prevent dhclient overwriting /etc/resolv.conf
  lineinfile: "dest=/etc/sysconfig/network-scripts/ifcfg-eth0 
              regexp='^PEERDNS=' 
              line='PEERDNS=\"no\"'
              state=present"

- name: create /etc/resolv.conf
  template: src=roles/common/templates/resolv.conf.j2 dest=/etc/resolv.conf owner=root group=root mode=0644
